scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8888' ]
        labels:
          application: 'Api Gate Way Service'

  - job_name: 'identity-service'
    metrics_path: '/identity/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application : 'Identity Service'


 #remember to add configuration for other services too
