server:
  port: 8086
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/file-service
cloudinary:
  cloudinary:
    cloud-name: ${CLOUD_NAME:}
    api-key: ${CLOUD_API_KEY:}
    api-secret: ${CLOUD_API_SECRET:}
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
